"""Short titles for the test case reference and Report (#12)."""

from collections.abc import Mapping
from types import MappingProxyType

TITLES: Mapping[str, str] = MappingProxyType(
    {
        "add_entity": "Entity appearing",
        "add_entity.entity_uuid": "Entity UUID",
        "block_entity_data": "Block entity data",
        "block_update": "Single block change",
        "block_update.block_state": "Single block change state",
        "block_update.pos.x": "Single block change x",
        "block_update.pos.y": "Single block change y",
        "block_update.pos.z": "Single block change z",
        "change_difficulty": "Difficulty",
        "chunk_batch_finished": "End of a chunk batch",
        "chunk_batch_finished.batch_size": "Chunks in a batch",
        "chunk_batch_start": "Start of a chunk batch",
        "commands.nodes[]": "Command node",
        "commands.nodes[].children[]": "Command node child",
        "commands.nodes[].flags": "Command node flags",
        "commands.nodes[].name": "Command node name",
        "commands.nodes[].parser": "Command argument type",
        "commands.nodes[].properties": "Command argument properties",
        "commands.nodes[].redirect_node": "Command redirect",
        "commands.nodes[].suggestions_type": "Command suggestions source",
        "configuration:custom_payload.channel": "Configuration plugin message channel",
        "configuration:custom_payload.data": "Configuration plugin message data",
        "configuration:update_tags.tagged_registries[].registry": "Tagged registry name",
        "configuration:update_tags.tagged_registries[].tags[]": "Tag",
        "configuration:update_tags.tagged_registries[].tags[].entries[]": "Tag member",
        "configuration:update_tags.tagged_registries[].tags[].tag_name": "Tag name",
        "container_set_content": "Inventory contents",
        "disconnect": "Kick",
        "disconnect.reason": "Kick reason",
        "forget_level_chunk": "Chunk unloaded",
        "game_event": "Game event",
        "initialize_border": "World border",
        "level_chunk_with_light": "Chunk",
        "level_chunk_with_light.light.block[]": "Block light in a chunk section",
        "level_chunk_with_light.light.sky[]": "Sky light in a chunk section",
        "level_chunk_with_light.sections[].biomes": "Biomes in a chunk section",
        "level_chunk_with_light.sections[].block_states": "Blocks in a chunk section",
        "level_event": "World event",
        "level_event.event_id": "World event type",
        "light_update": "Light update",
        "light_update.data.block[]": "Block light update",
        "light_update.data.sky[]": "Sky light update",
        "login.enforces_secure_chat": "Secure chat required",
        "login.is_flat": "Flat world flag",
        "login.sea_level": "Sea level",
        "login_compression.threshold": "Compression threshold",
        "login_finished.profile.username": "Player name at login",
        "login_finished.profile.uuid": "Player UUID at login",
        "play:post_effects": "Screen effects",
        "player_abilities": "Player abilities",
        "player_info_remove.uuids[]": "Player leaving the list",
        "player_info_update": "Player list update",
        "player_info_update.actions[]": "Player list update part",
        "player_info_update.players[].chat_session": "Player chat session",
        "player_info_update.players[].display_name": "Player list display name",
        "player_info_update.players[].name": "Player name in the list",
        "player_info_update.players[].uuid": "Player UUID in the list",
        "player_position": "Player position",
        "player_position.teleport_id": "Teleport number",
        "player_position.x": "Player position x",
        "player_position.y": "Player position y",
        "player_position.z": "Player position z",
        "recipe_book_add": "Recipes in the recipe book",
        "recipe_book_settings": "Recipe book settings",
        "registry_data.entries[]": "Registry entry",
        "registry_data.entries[].data": "Registry entry data",
        "registry_data.entries[].entry_id": "Registry entry name",
        "registry_data.registry_id": "Registry name",
        "section_blocks_update": "Block changes in a section",
        "section_blocks_update.blocks[]": "Block change in a section",
        "section_blocks_update.blocks[].state": "Block state in a section change",
        "section_blocks_update.blocks[].x": "Block x in a section change",
        "section_blocks_update.blocks[].y": "Block y in a section change",
        "section_blocks_update.blocks[].z": "Block z in a section change",
        "section_blocks_update.section.y": "Section height",
        "select_known_packs.known_packs[].id": "Known pack ID",
        "select_known_packs.known_packs[].namespace": "Known pack namespace",
        "select_known_packs.known_packs[].version": "Known pack version",
        "server_data": "Server description in play",
        "set_default_spawn_position": "World spawn point",
        "remove_entities": "Entities disappearing",
        "remove_entities.entity_ids[]": "Entity disappearing",
        "set_entity_data": "Entity data",
        "set_entity_data.entries[].index": "Entity data field",
        "set_entity_data.entries[].serializer": "Entity data type",
        "set_entity_data.entries[].value": "Entity data value",
        "set_entity_motion": "Entity velocity",
        "set_experience": "Experience",
        "set_health": "Health and food",
        "set_held_slot": "Selected hotbar slot",
        "status:pong_response.timestamp": "Server list ping response",
        "status_response.description": "Server list description",
        "status_response.description.text": "Server list description text",
        "status_response.enforceSecureChat": "Unused secure chat flag",
        "status_response.favicon": "Server list icon",
        "status_response.players.max": "Player limit",
        "status_response.players.online": "Online players",
        "status_response.players.sample": "Server list player sample",
        "status_response.players.sample[].id": "Server list player UUID",
        "status_response.players.sample[].name": "Server list player name",
        "status_response.version.name": "Server version name",
        "status_response.version.protocol": "Protocol version",
        "system_chat": "Chat message from the server",
        "system_chat.content": "Chat message text",
        "ticking_state": "Tick rate and freeze state",
        "ticking_step": "Tick steps",
        "update_advancements": "Advancements",
        "update_attributes": "Entity attributes",
        "update_enabled_features.feature_flags[]": "Enabled feature flag",
        "update_recipes": "Recipe data",
    }
)
"""Known test case name → the short title checked against the docs reference."""
