"""Particles: a VarInt registry id, then that type's options (`ParticleTypes.STREAM_CODEC`).

Pinned with `javap` on the 26.3 server jar: the registration order of `ParticleTypes` gives
the ids (0 to 127), and each type's `streamCodec` its options. 22 types carry options; the
rest carry none. A particle is `{"type": "minecraft:dust", "options": {...}}`, the options
being None for a type that has none. Colors are signed Ints as vanilla writes them (ARGB or
RGB). A block state is its id in the global block state registry, not range checked.
"""

from mscts.codec.components import ITEM_STACK_TEMPLATE
from mscts.codec.schema import (
    DOUBLE,
    ENTITY_ID,
    FLOAT,
    INT,
    POSITION,
    VAR_INT,
    Schema,
    Tagged,
    WireType,
)

POSITION_SOURCE = Tagged(
    "type",
    "value",
    (
        ("minecraft:block", POSITION),
        ("minecraft:entity", Schema(entity_id=ENTITY_ID, y_offset=FLOAT)),
    ),
)
"""A `PositionSource` (the registry ids of `position_source_type`: block 0, entity 1)."""

_NAMES = (
    "angry_villager",
    "block",
    "block_marker",
    "bubble",
    "sulfur_bubbles",
    "noxious_gas",
    "noxious_gas_cloud",
    "geyser",
    "geyser_base",
    "geyser_poof",
    "geyser_plume",
    "cloud",
    "copper_fire_flame",
    "crit",
    "damage_indicator",
    "dragon_breath",
    "dripping_lava",
    "falling_lava",
    "landing_lava",
    "dripping_water",
    "falling_water",
    "dust",
    "dust_color_transition",
    "effect",
    "elder_guardian",
    "enchanted_hit",
    "enchant",
    "end_rod",
    "entity_effect",
    "explosion_emitter",
    "explosion",
    "gust",
    "small_gust",
    "gust_emitter_large",
    "gust_emitter_small",
    "sonic_boom",
    "falling_dust",
    "firework",
    "fishing",
    "flame",
    "infested",
    "cherry_leaves",
    "pale_oak_leaves",
    "red_poplar_leaves",
    "orange_poplar_leaves",
    "yellow_poplar_leaves",
    "tinted_leaves",
    "sculk_soul",
    "sculk_charge",
    "sculk_charge_pop",
    "soul_fire_flame",
    "soul",
    "flash",
    "happy_villager",
    "composter",
    "heart",
    "instant_effect",
    "item",
    "vibration",
    "trail",
    "pause_mob_growth",
    "reset_mob_growth",
    "item_slime",
    "item_cobweb",
    "item_snowball",
    "large_smoke",
    "lava",
    "mycelium",
    "note",
    "poof",
    "portal",
    "rain",
    "smoke",
    "white_smoke",
    "sneeze",
    "spit",
    "squid_ink",
    "sweep_attack",
    "totem_of_undying",
    "underwater",
    "splash",
    "witch",
    "bubble_pop",
    "current_down",
    "bubble_column_up",
    "nautilus",
    "dolphin",
    "campfire_cosy_smoke",
    "campfire_signal_smoke",
    "dripping_honey",
    "falling_honey",
    "landing_honey",
    "falling_nectar",
    "falling_spore_blossom",
    "ash",
    "crimson_spore",
    "warped_spore",
    "spore_blossom_air",
    "dripping_obsidian_tear",
    "falling_obsidian_tear",
    "landing_obsidian_tear",
    "reverse_portal",
    "white_ash",
    "small_flame",
    "snowflake",
    "dripping_dripstone_lava",
    "falling_dripstone_lava",
    "dripping_dripstone_water",
    "falling_dripstone_water",
    "glow_squid_ink",
    "glow",
    "wax_on",
    "wax_off",
    "electric_spark",
    "scrape",
    "shriek",
    "egg_crack",
    "dust_plume",
    "trial_spawner_detection",
    "trial_spawner_detection_ominous",
    "vault_connection",
    "dust_pillar",
    "ominous_spawning",
    "raid_omen",
    "trial_omen",
    "block_crumble",
    "firefly",
    "sulfur_cube_goo",
)
"""Every particle type, in registration order: the index is the id."""

_BLOCK = Schema(block_state=VAR_INT)
_GEYSER = Schema(water_blocks=INT)
_GEYSER_BASE = Schema(water_blocks=INT, burst_impulse_base=FLOAT)
_SPELL = Schema(color=INT, power=FLOAT)
_COLOR = Schema(color=INT)

_OPTIONS: dict[str, WireType[object]] = {
    "block": _BLOCK,
    "block_marker": _BLOCK,
    "falling_dust": _BLOCK,
    "dust_pillar": _BLOCK,
    "block_crumble": _BLOCK,
    "geyser": _GEYSER,
    "geyser_plume": _GEYSER,
    "geyser_base": _GEYSER_BASE,
    "geyser_poof": _GEYSER_BASE,
    "dragon_breath": Schema(power=FLOAT),
    "dust": Schema(color=INT, scale=FLOAT),
    "dust_color_transition": Schema(from_color=INT, to_color=INT, scale=FLOAT),
    "effect": _SPELL,
    "instant_effect": _SPELL,
    "entity_effect": _COLOR,
    "tinted_leaves": _COLOR,
    "flash": _COLOR,
    "sculk_charge": Schema(roll=FLOAT),
    # The item particle's options are an item stack template (an item, a count, components).
    "item": ITEM_STACK_TEMPLATE,
    "vibration": Schema(destination=POSITION_SOURCE, arrival_in_ticks=VAR_INT),
    "trail": Schema(target=Schema(x=DOUBLE, y=DOUBLE, z=DOUBLE), color=INT, duration=VAR_INT),
    "shriek": Schema(delay=VAR_INT),
}

PARTICLE = Tagged(
    "type", "options", tuple((f"minecraft:{name}", _OPTIONS.get(name)) for name in _NAMES)
)
"""A particle, with its options: `{"type": "minecraft:block", "options": {"block_state": 1}}`."""
