"""The committed registry name lists, in protocol id order, and the number of block states.

They live in `codec/data/<version>/registry_names.json` and `block_states.json`, generated by
`mise run regen:packets` from the vanilla data generator's registry and block reports, so a
name's position is its protocol id and no id or count is ever typed by hand.
"""

import json
from functools import cache
from importlib import resources
from typing import cast


@cache
def _load(minecraft_version: str) -> dict[str, tuple[str, ...]]:
    resource = resources.files("mscts.codec").joinpath(
        "data", minecraft_version, "registry_names.json"
    )
    lists = cast("dict[str, list[str]]", json.loads(resource.read_text(encoding="utf-8")))
    return {registry: tuple(names) for registry, names in lists.items()}


def registry_names(minecraft_version: str, registry: str) -> tuple[str, ...]:
    """The names of `registry`'s entries, indexed by protocol id, for a Minecraft version.

    Only the registries in `regen.REGISTRY_NAME_LISTS` are committed.

    Raises:
        FileNotFoundError: There is no data for that version.
        KeyError: The registry is not one of the committed lists.
    """
    return _load(minecraft_version)[registry]


@cache
def block_state_count(minecraft_version: str) -> int:
    """How many block states a Minecraft version has: its block state ids are 0 to this - 1.

    The client's global block state palette is that size, so it sets the width of a direct
    block container in a chunk (docs/research/2026-10-02-chunks-light.md).

    Raises:
        FileNotFoundError: There is no data for that version.
    """
    resource = resources.files("mscts.codec").joinpath(
        "data", minecraft_version, "block_states.json"
    )
    counts = cast("dict[str, int]", json.loads(resource.read_text(encoding="utf-8")))
    return counts["count"]
