"""The committed registry name lists, in protocol id order.

They live in `codec/data/<version>/registry_names.json`, generated by `mise run
regen:packets` from the vanilla data generator's registry report, so a name's position is
its protocol id and no id is ever typed by hand.
"""

import json
from functools import cache
from importlib import resources
from typing import cast


@cache
def _load(minecraft_version: str) -> dict[str, tuple[str, ...]]:
    resource = resources.files("mscts.codec").joinpath(
        "data", minecraft_version, "registry_names.json"
    )
    lists = cast("dict[str, list[str]]", json.loads(resource.read_text(encoding="utf-8")))
    return {registry: tuple(names) for registry, names in lists.items()}


def registry_names(minecraft_version: str, registry: str) -> tuple[str, ...]:
    """The names of `registry`'s entries, indexed by protocol id, for a Minecraft version.

    Only the registries in `regen.REGISTRY_NAME_LISTS` are committed.

    Raises:
        FileNotFoundError: There is no data for that version.
        KeyError: The registry is not one of the committed lists.
    """
    return _load(minecraft_version)[registry]
