"""The committed registry name lists, in protocol id order, block state count and item defaults.

They live in `codec/data/<version>/registry_names.json`, `block_states.json` and `items.json`,
generated by `mise run regen:packets` from the vanilla data generator's registry, block and item
component reports, so a name's position is its protocol id and no id or count is ever typed by
hand.
"""

import json
from collections.abc import Mapping
from functools import cache
from importlib import resources
from types import MappingProxyType
from typing import cast


@cache
def _load(minecraft_version: str) -> dict[str, tuple[str, ...]]:
    resource = resources.files("mscts.codec").joinpath(
        "data", minecraft_version, "registry_names.json"
    )
    lists = cast("dict[str, list[str]]", json.loads(resource.read_text(encoding="utf-8")))
    return {registry: tuple(names) for registry, names in lists.items()}


def registry_names(minecraft_version: str, registry: str) -> tuple[str, ...]:
    """The names of `registry`'s entries, indexed by protocol id, for a Minecraft version.

    Only the registries in `regen.REGISTRY_NAME_LISTS` are committed.

    Raises:
        FileNotFoundError: There is no data for that version.
        KeyError: The registry is not one of the committed lists.
    """
    return _load(minecraft_version)[registry]


@cache
def block_state_count(minecraft_version: str) -> int:
    """How many block states a Minecraft version has: its block state ids are 0 to this - 1.

    The client's global block state palette is that size, so it sets the width of a direct
    block container in a chunk (docs/research/2026-10-02-chunks-light.md).

    Raises:
        FileNotFoundError: There is no data for that version.
    """
    resource = resources.files("mscts.codec").joinpath(
        "data", minecraft_version, "block_states.json"
    )
    counts = cast("dict[str, int]", json.loads(resource.read_text(encoding="utf-8")))
    return counts["count"]


@cache
def _items(minecraft_version: str) -> dict[str, dict[str, object]]:
    resource = resources.files("mscts.codec").joinpath("data", minecraft_version, "items.json")
    return cast("dict[str, dict[str, object]]", json.loads(resource.read_text(encoding="utf-8")))


def max_stack_sizes(minecraft_version: str) -> Mapping[str, int]:
    """Each item's default stack size, by name, for the items whose stack size is not 64.

    From `codec/data/<version>/items.json`, generated from the item component reports.

    Raises:
        FileNotFoundError: There is no data for that version.
    """
    return cast("Mapping[str, int]", MappingProxyType(_items(minecraft_version)["max_stack_size"]))


def equipment_slots(minecraft_version: str) -> Mapping[str, str]:
    """Each equippable item's equipment slot (`head`, `offhand`, `body`, ...), by name.

    From `codec/data/<version>/items.json`, generated from the item component reports.

    Raises:
        FileNotFoundError: There is no data for that version.
    """
    return cast("Mapping[str, str]", MappingProxyType(_items(minecraft_version)["equippable"]))
